//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an art with corresponding id: {0}.
        /// </summary>
        internal static string ArtByIdNotFound {
            get {
                return ResourceManager.GetString("ArtByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any arts.
        /// </summary>
        internal static string ArtsNotFound {
            get {
                return ResourceManager.GetString("ArtsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any audios.
        /// </summary>
        internal static string AudiosNotFound {
            get {
                return ResourceManager.GetString("AudiosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any categories.
        /// </summary>
        internal static string CategoriesNotFound {
            get {
                return ResourceManager.GetString("CategoriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any fact.
        /// </summary>
        internal static string FactsNotFound {
            get {
                return ResourceManager.GetString("FactsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any historical contexts.
        /// </summary>
        internal static string HistoricalContextsNotFound {
            get {
                return ResourceManager.GetString("HistoricalContextsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any images.
        /// </summary>
        internal static string ImagesNotFound {
            get {
                return ResourceManager.GetString("ImagesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news in the database.
        /// </summary>
        internal static string NewsNotFound {
            get {
                return ResourceManager.GetString("NewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners.
        /// </summary>
        internal static string PartnersNotFound {
            get {
                return ResourceManager.GetString("PartnersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any related terms.
        /// </summary>
        internal static string RelatedTermsNotFound {
            get {
                return ResourceManager.GetString("RelatedTermsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No streetcodes exist now.
        /// </summary>
        internal static string StreetcodesNotFound {
            get {
                return ResourceManager.GetString("StreetcodesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any subtitles.
        /// </summary>
        internal static string SubtitlesNotFound {
            get {
                return ResourceManager.GetString("SubtitlesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any tags.
        /// </summary>
        internal static string TagsNotFound {
            get {
                return ResourceManager.GetString("TagsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team links.
        /// </summary>
        internal static string TeamLinksNotFound {
            get {
                return ResourceManager.GetString("TeamLinksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team.
        /// </summary>
        internal static string TeamsNotFound {
            get {
                return ResourceManager.GetString("TeamsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any terms.
        /// </summary>
        internal static string TermsNotFound {
            get {
                return ResourceManager.GetString("TermsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any texts.
        /// </summary>
        internal static string TestsNotFound {
            get {
                return ResourceManager.GetString("TestsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any timelineItem.
        /// </summary>
        internal static string TimelineItemsNotFound {
            get {
                return ResourceManager.GetString("TimelineItemsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any transaction link.
        /// </summary>
        internal static string TransactionLinksNotFound {
            get {
                return ResourceManager.GetString("TransactionLinksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any videos.
        /// </summary>
        internal static string VideosNotFound {
            get {
                return ResourceManager.GetString("VideosNotFound", resourceCulture);
            }
        }
    }
}
